name: Verify and Sign Image

on:
  push:
    branches:
      - main

jobs:
  verify-and-sign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Read the hash from the file and store it in an environment variable
      - name: Read Digest File
        id: read-digest
        run: |
          echo "DIGEST=$(cat digest)" >> $GITHUB_ENV

      # Step 3: Verify the image using the hash
      - name: Verify Image with Cosign
        run: |
          cosign verify ghcr.io/aditsachde/confidential-witness@sha256:${DIGEST} \
            --certificate-identity="https://github.com/aditsachde/confidential-witness/.github/workflows/build.yml@refs/heads/main" \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com

      # Step 4: Tag the image
      - name: Tag Image
        run: |
          IMAGE_TO_TAG="ghcr.io/aditsachde/confidential-witness@sha256:${DIGEST}"
          NEW_TAG="ghcr.io/aditsachde/containersigningtestrepo:latest"
          docker pull $IMAGE_TO_TAG
          docker tag $IMAGE_TO_TAG $NEW_TAG
          docker push $NEW_TAG

      # Step 5: Setup authentication keys
      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/556654538773/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'


      # Step 6: Sign the image with Cosign
      - name: Sign Image with Cosign
        run: |
          cosign sign --yes --key gcpkms://projects/mineral-oarlock-443418-j9/locations/us-central1/keyRings/signing-keyring/cryptoKeys/signing-key/cryptoKeyVersions/1 \
            ghcr.io/aditsachde/containersigningtestrepo:latest
