name: Publish Audit Logs

on:
  push:
    branches:
      - main

jobs:
  verify-and-sign:
    runs-on: ubuntu-latest
    steps:
      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/556654538773/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'

      - run: |
          gcloud kms keys versions get-public-key projects/mineral-oarlock-443418-j9/locations/us-central1/keyRings/witness-keyring3/cryptoKeys/witness-key3/cryptoKeyVersions/1
          gcloud logging read "logName=projects/mineral-oarlock-443418-j9/logs/cloudaudit.googleapis.com%2Factivity" --freshness="400d" > /dev/null
